blank_issues_enabled: false
contact_links:
 - name: Monacoin Official Forum
   url: https://github.com/monacoinproject/monacoin/discussions
   about: Please post general questions, support requests, and discussions here.
